### ISSUE TITLE
Add commands of create, list, run and delete for git workspace

### ISSUE THREAD

**Issue by craftslab** [repo-scm/git#11]
## Create git workspace

```bash
# Create workspace for local repo
git create /local/repo [--name string]

# Create workspace for remote repo
git create user@host:/remote/repo [--name string]
```

> **Notes**: Workspace name is set to `<repo_name>-<7_bit_hash>` in default if `--name string` not set.

## List git workspaces

```bash
# List a workspace
git list <workspace_name>

# List a workspace in verbose mode
git list <workspace_name> --verbose

# List all workspaces
git list --all

# List all workspaces in verbose mode
git list --all --verbose
```

## Run git workspace

```bash
git run <workspace_name>
```

## Delete git workspace

```bash
# Delete a workspace
git delete <workspace_name>

# Delete all workspaces
git delete --all
```

## Settings

Settings can be set in the directory `$HOME/.repo-scm/git.yaml`.

An example of `$HOME/.repo-scm/git.yaml` as below:

```yaml
models:
  - provider_name: "litellm"
    api_base: "http://localhost:4000"
    api_key: "noop"
    model_id: "anthropic/claude-opus-4-20250514"
overlay:
  mount: "/mnt/repo-scm/git/overlay"
sshfs:
  mount: "/mnt/repo-scm/git/sshfs"
  options: [
    "allow_other,default_permissions,follow_symlinks",
    "cache=yes,kernel_cache,compression=no,big_writes,cache_timeout=115200",
    "Cipher=aes128-ctr,StrictHostKeyChecking=no,UserKnownHostsFile=/dev/null",
  ]
  ports: [
    22,
  ]
```
