### ISSUE TITLE
Add commands of chat and mcp for git workspace

### ISSUE THREAD

**Issue by craftslab** [repo-scm/git#12]
## Chat with git workspace

```bash
# Chat with workspace in interactive mode
git chat <workspace_name> [prompt] [--model string]

# Chat with workspace in quiet mode
git chat <workspace_name> [prompt] [--model string] --quiet
```

> **Notes**: Model name is set to `litellm/anthropic/claude-opus-4-20250514` in default if `--model string` not set.

## MCP for git workspace

```bash
git mcp <workspace_name>
```

## Settings

Settings can be set in the directory `$HOME/.repo-scm/git.yaml`.

An example of `$HOME/.repo-scm/git.yaml` as below:

```yaml
models:
  - provider_name: "litellm"
    api_base: "http://localhost:4000"
    api_key: "noop"
    model_id: "anthropic/claude-opus-4-20250514"
overlay:
  mount: "/mnt/repo-scm/git/overlay"
sshfs:
  mount: "/mnt/repo-scm/git/sshfs"
  ports: [
    22,
  ]
```
