### ISSUE TITLE
Add commands of lint, build and exec for git workspace

### ISSUE THREAD

**Issue by craftslab** [repo-scm/git#13]
## Lint git workspace

```bash
git lint <workspace_name>
```

## Build git workspace

```bash
git build <workspace_name>
```

## Execute git workspace

```bash
git exec <workspace_name>
```

## Settings

Settings can be set in the directory `$HOME/.repo-scm/git.yaml`.

An example of `$HOME/.repo-scm/git.yaml` as below:

```yaml
models:
  - provider_name: "litellm"
    api_base: "http://localhost:4000"
    api_key: "noop"
    model_id: "anthropic/claude-opus-4-20250514"
overlay:
  mount: "/mnt/repo-scm/git/overlay"
sshfs:
  mount: "/mnt/repo-scm/git/sshfs"
  options: [
    "allow_other,default_permissions,follow_symlinks",
    "cache=yes,kernel_cache,compression=no,big_writes,cache_timeout=115200",
    "Cipher=aes128-ctr,StrictHostKeyChecking=no,UserKnownHostsFile=/dev/null",
  ]
  ports: [
    22,
  ]
```
