### ISSUE TITLE
Add commands of create, run, list and delete for git workspace

### ISSUE THREAD

**Issue by craftslab** [repo-scm/git#3]
## Create git workspace

```bash
# Create workspace for local repo
git create /local/repo [--name string]

# Create workspace for remote repo
git create user@host:/remote/repo [--name string]
```

> Notes: workspace name is set to `<repo_name>-<7_bit_hash>` in default if `--name string` not set.

## List git workspaces

```bash
git list workspaces
```

## Run git workspace

```bash
git run <workspace_name>
```

## Delete git workspace

```bash
git delete <workspace_name>
```

## Settings

Settings can be set in the directory `$HOME/.repo-scm/git.yaml`.

An example of `$HOME/.repo-scm/git.yaml` as below:

```yaml
overlay:
  mount: "/mnt/repo-scm/git/overlay"
sshfs:
  mount: "/mnt/repo-scm/git/sshfs"
  options:
    - "allow_other,default_permissions,follow_symlinks"
    - "cache=yes,kernel_cache,compression=no,big_writes,cache_timeout=115200"
    - "Cipher=aes128-ctr,StrictHostKeyChecking=no,UserKnownHostsFile=/dev/null"
  ports:
    - 22
```
